### ISSUE TITLE
Remove unused or no-longer-useful scripts

### ISSUE THREAD

**Issue by egillespie** [lansingcodes/slackbot#38]
**Is your feature request related to a problem? Please describe.**

Some scripts were created for testing or for one-off projects that are not relevant to the Slack team as a whole. Leaving them around makes it unclear what features should be supported by the slackbot and even though the scripts aren't used, they can still be the source of bugs.

**Describe the solution you'd like**

Remove the unused or no-longer-useful scripts, tests, and dead supporting code.

**Additional context**

The following scripts are good candidates for removal:

- `lib/initializers/fuck-shit-up.ls`
- `lib/initializers/http-status-code-lookup.ls` (also remove `cheerio` dependency)
- `lib/initializers/watch-for-standup-participation.ls`
- `lib/scheduled-tasks/prompt-standup.ls`
- `lib/scheduled-tasks/remind-about-standup.ls`

These external scripts could also be removed:

- `hubot-google-translate`
- `hubot-pugme`

**Comment by lucidmachine** [comment]
Closed with #41
