### ISSUE TITLE
Establish Style Guidelines and Tools

### ISSUE THREAD

**Issue by lucidmachine** [lansingcodes/slackbot#44]
**Is your feature request related to a problem? Please describe.**
This project uses [JavaScript Standard Style](https://standardjs.com/index.html). This isn't currently explicitly stated anywhere or supported by tools in the project.

**Describe the solution you'd like**
Add documentation and tooling for the style.

* Add a brief style section to CONTRIBUTING.md.
* Add the linter and [editor plugins](https://standardjs.com/#are-there-text-editor-plugins) as tools in CONTRIBUTING.md.
* Add a script to run the linter in package.json.
* Add a script to run the linter in fix mode in package.json.
* Optional: Add the linter as part of the "test" script in package.json so that non-conformant code fails the build.
* Optional: Remove .editorconfig. One of JavaScript Standard Style's stated goals is to replace such configuration files.

**Comment by egillespie** [comment]
I also recommend adding a `precommit` script to `package.json` that invokes the linter so that unlinted code fails to commit.
